data_extract:
  catch_up: true
  expireAfterSeconds: 60*60*24*7
  last_fetch_records: None
  reset: false
  window_size:
    15m: 5
    30m: 20
    5m: 5
data_ingest:
  desried_symbols:
  - QQQ
  - SPY
  - SOXX
  - DJIA
  - IWM
  - NVDA
  - AAPL
  - TSLA
  - AMZN
  - MSFT
  - SQQQ
  - AMD
  - SOXL
  - SOXS
  - GOOGL
  - NVDS
  - NFLX
  - UPRO
  - SPXL
  - SPXS
  - TQQQ
  - TNA
  - TZA
  - TSLS
  - TSLL
  - SDOW
data_preprocess:
  new_intervals:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
datastream_transform:
  expireAfterSeconds: 60*60*24*7
